import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { ClerkProvider } from "@clerk/nextjs";
import { QueryProviders } from "@/providers/query-provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hello Financial System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* 首页排除QueryProviders的渲染 */}
          <QueryProviders>
            {children}
          </QueryProviders>
        </body>
      </html>
    </ClerkProvider>
    
  );
}
